sudo: required
language: go
go:
- 1.8
services:
- docker
after_success:
- source ./build/travis-utils.sh
- if is_travis_push_env; then docker login -u $DOCKER_USER -p $DOCKER_PASSWORD; fi
- if is_travis_push_env; then make push; fi
- if is_travis_release_env; then make push-latest; fi
env:
  global: