sudo: required
language: go
go:
- 1.8
services:
- docker
after_success:
- source ./build/travis-utils.sh
- if is_travis_push_env; then docker login -u $DOCKER_USER -p $DOCKER_PASSWORD; fi
- if is_travis_push_env; then make push; fi
- if is_travis_release_env; then make push-latest; fi
env:
  global:
    - secure: "FYieYrB4mh2JZlxrsiKiMn1KsuJ2E0a5XTGqdmuQY+czhrwxnX7PBntxx3g1FWgaBLtfyS1r3A5LBsf0NEgYsfZtl0JDkhoECAhvPR4gUTD42+oySTqH9tyZo21zTPddNo8vITeBa+T+vpfNlRvMy7aVSaYs45+jgjkUGnXpjDgs1kkoeMfIwVJXlRur70MD7rrb7Ob4TqVsFE5xsRWq5sbrpPx8vcx/Qf/W5UHj9K+w3d+38lcFgAP0vYCMRDFvs9V5iN2lCLsa1SyNONC8ckDqM8ctcM6TgexM/yN+noOAplukPJMt3KCPvWHZwlj9dP/HN6lYK/f40tkc5dXXllOW4KxYmyEWcY8Pu3EPDESQjWO4PWE9zJ9IQGJ02T0Ox8E0vJ6NQw09gdk5ePinwn1C1x/icPTUwWrjJeiI5xyjlWz+sYoBRjSzBv6LbSaB/ZaPWl9AVduy8lS6aYDB353lKdj6Qy6R/uqZ2D2rOgMXo/FMeeuwXpuT4hxNzC+82MeMEJj0Bsj9lAZs8R6URTDPHM8KVFh0gkzFWqsec4QBfMxv9IWUGKdxEDKlbIeCdFIryOzZwZBTxgwS0aTF9fCfWz8roNz6Lr5oxDu4ocm8F6oIvW4opcj+kR/D09+7+pYs3K9bNbgXMDbz1RH767GqjWNBloqwevF9QrtJL6I="
    - secure: "ijuS4LSIneUCtcmP0KRlPh56casDYJeUDaNmoMMsdraNsKJ1WhlVwghWXgDQ6aIMMmhkd6xH3MuzXKg65nfOW6OxOuzglquGr8QMDRbOGCe591mnih8h3bMgGZc2CX5zeB3BphvmaQEL2qOduGXUSKC4a9Oyo4dH6ThD5tBV3F0Y7PxfPqol4G7aYOdRKpGYr5xefVXcEglwNAMB6WIMEd4TzIw7vL4dX34WdES07WMfNGRT/aYP8Qy6cUGmfUNLsbQc/sThfhFgshqeggvqBGvvT3dXnx45xY5MtVIwrd/99SDvSZ13Rv6eA8iqhvaPFU/4rHpzxlRQkZ3IBvLn8wJCEGHtEGDeuKiUA8DzJ6yKJYTuxJJozkUKEw7v0X65nV1E04WQPCt7uRBDg/VfsyZeqsZVDnAxOk/VboTJ83UPc86PVFx19LrGRt876Hy6ERzHI0X9GU+2YuCN0w1cxsYSJ6KPmjcIh04dFnlRXR5LS2i8BR/Py/D4d9B8raAJTyEhQhHjf5CpZ47HRZNHpJCspuN4E/VTGWDpObZzauMsPDpJidf1C8IPUGbT1iYPhOwCzIyEEZ+xhom7Oene4A4fj6udhoR+Ir6QraZgTxxzvXBK7BSe6wNa601gghrP8iS6mIbGLQQN3KfzsP6L8FuY5Pt2bN54a72TfOZt5bo="